### ISSUE TITLE
PR5 breaks Nim version <= 2.0

### ISSUE THREAD

**Issue by ThomasTJdev** [OpenSystemsLab/otp.nim#6]
The new PR https://github.com/OpenSystemsLab/otp.nim/pull/5 implementing [`stack_strings`](https://github.com/termermc/nim-stack-strings/blob/master/stack_strings.nimble) only supports Nim v2.0 and breaks the `opt` package on Nim <= 2.0.

The `otp.nimble` is set for supporting Nim v1.6.10 and the code in `opt.nim` includes Nim version checks:
https://github.com/OpenSystemsLab/otp.nim/blob/8278f63524c48fb1b13ab070127d17254b290807/otp.nim#L33-L35

In the event that the package will not support Nim versions <= 2.0 I would suggest that the last supported version-tag for Nim <= 2.0 is mentioned in the readme, so users can require that, instead of relying on the latest tag.

**Comment by beef331** [comment]
Whoops I did not realize stack_strings was 2.0+.

**Comment by ThomasTJdev** [comment]
Thanks @beef331 . Maybe a GitHub action running the test with a matrix for Nim versions would be a good idea? I can add a PR if it is.

**Comment by beef331** [comment]
No problem seems good to me, but I'm just a numpty sending PRs :smile:
